apiVersion: v2
name: fastgateway
description: A Helm chart for FastGateway - Kubernetes Gateway API Management Platform
type: application
version: 1.3.2
appVersion: "0.4.0"
keywords:
  - gateway
  - kubernetes
  - envoy
  - api-management
home: https://fastgateway.dev
icon: https://raw.githubusercontent.com/fastgateway-dev/helm-chart/main/fastgateway/logo.png
sources:
  - https://github.com/fastgateway-dev/helm-chart
  - https://github.com/fastgateway-dev/backend-v2
  - https://github.com/fastgateway-dev/frontend-v2
maintainers:
  - name: zufardhiyaulhaq
