apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastgateway.fullname" . }}
  labels:
    {{- include "fastgateway.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ADMIN_USERNAME: {{ .Values.config.adminUsername | quote }}
  ADMIN_EMAIL: {{ .Values.config.adminEmail | quote }}
