{{- if eq .Values.database.type "internal" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastgateway.fullname" . }}-database
  labels:
    {{- include "fastgateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.internal.username | quote }}
  password: {{ .Values.database.internal.password | quote }}
  database: {{ .Values.database.internal.database | quote }}
{{- end }}
